workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
                PACKAGE_NAME: "com.mainapp" # <-- Put your package name here e.g. com.domain.myapp
                CM_KEYSTORE: mash.keystore # <-- Put your encrypted keystore file here
                CM_KEYSTORE_PASSWORD: 123456 # <-- Put your encrypted keystore password here
                CM_KEY_ALIAS_PASSWORD: 123456 # <-- Put your encrypted keystore alias password here
                CM_KEY_ALIAS_USERNAME: mash # <-- Put your encrypted keystore alias username here 
            node: latest
        scripts:
            - name: Install npm dependencies
              script: |
                                npm install
            - name: Set Android SDK location
              script: |
                                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
            - name: Set up keystore
              script: |
                    echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
                    cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
                    storePassword=$CM_KEYSTORE_PASSWORD
                    keyPassword=$CM_KEY_ALIAS_PASSWORD
                    keyAlias=$CM_KEY_ALIAS_USERNAME
                    storeFile=/tmp/keystore.keystore
                    EOF   
            # - name: Tests                       # Insert before the build command
            #   script: npm test                                
            - name: Build Android release
              script: |
                # Set environment variable so it can be used to increment build number in android/app/build.gradle
                # Note that tracks can be specified when retrieving latest build number from Google Play, for example:
                # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))
                # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
                cd android && ./gradlew assembleRelease                
        artifacts:
            - android/app/build/outputs/codemagic/jesttest.apk